### ISSUE TITLE
Rails: Errors with relation `has_and_belongs_to_many`

### ISSUE THREAD

**Issue by MGatner** [applandinc/appmap-ruby#226] opened 2022-03-09 20:16 UTC
Models with a `has_and_belongs_to_many` relationship are causing a strange runtime error when trying to map with Minitest:
```
Error:

RuntimeError: Wrapped undumpable exception for: ArgumentError: Class name cannot be blank. You need to supply a name argument when anonymous class given
    app/models/instance.rb:6:in `<class:Instance>'
    app/models/instance.rb:3:in `<top (required)>'
```

The model files are very basic:
```
# frozen_string_literal: true

class Instance < ApplicationRecord
  belongs_to :course
  has_and_belongs_to_many :instructor
end
```
```
# frozen_string_literal: true

class Instructor < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :instance
end
```

Removing the relations clears up the error.

***

Ruby: 3.1.0
Rails: 7.0.2.2
AppMap: 0.73.0

**Comment by MGatner** [comment] 2022-03-25 14:37
Any maintainers have guidance? I found nothing helpful in docs or popular internet websites. I'm happy to do some sleuthing but need a starting point.

**Comment by apotterri** [comment] 2022-03-25 18:00
I've found the cause of this error. Working on a fix now, should be available in the next couple of days.

**Comment by apotterri** [comment] 2022-03-28 12:46
I've got a fix for this in-progress. However, while I was testing it, I found that there are other issues generating AppMaps in a Rails 7 app.

@MGatner Until the issues with Rails 7 get sorted out, you may have better luck with Rails 6.

**Comment by MGatner** [comment] 2022-03-28 13:07
> I've got a fix for this in-progress.
🥳
> better luck with Rails 6.
Unfortunately this is not an option, but thank you for the updates! The Swagger command still generated a semi-useful skeleton, so any fixes that result in improvements will still be beneficial. If I end up filling this in the rest of the way by hand AppMaps has still saved me oodles of time.

**Comment by kgilpin** [comment] 2022-03-28 14:22
@apotterri can he work around this by adding the offending classes to the `exclude` list?

**Comment by apotterri** [comment] 2022-03-28 18:34
I don't think so, no. Rails generates these classes at runtime, to represent instances of associations. They don't appear to have names: `cls.name` here https://github.com/applandinc/appmap-ruby/pull/235/files#diff-b0ca8eba4336df106cde97666ff16fea18485c28580c509363d377ea3b506229R460 is an empty string.

(I think this also answers the question you raised here: https://github.com/applandinc/appmap-ruby/pull/235#issuecomment-1080615051, at least in the context of this PR.)

**Closed** 2022-03-29 12:50 UTC

**Comment by MGatner** [comment] 2022-05-09 17:59
Hi all, sorry for the long delay. Just picking this back up. Unfortunately the latest release (`0.83.1`) appears to be working even less than before. Running the tests works (though with a cryptic warning message):
```bash
$ APPMAP=true bundle exec rails test
process_action not found on ActionController::Instrumentation
process_action not found on ActionController::Instrumentation

Run options: --seed 41334
...
```

But then when I try to generate the docs I now get empty scaffolds:
```yaml
---
openapi: 3.0.1
info:
  title: Enroll API
  version: v1
paths: {}
components: 
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
```

In the previous version this at least had a helpful base that I cold finish filling out myself.

**Comment by kgilpin** [comment] 2022-05-09 18:15
This seems like a new problem so I will open a new Issue for it.

**Comment by MGatner** [comment] 2022-05-10 10:42
Thanks! Yes we are able to use the semi-functional solution with the older version. I will follow the new issue, thank you for making it.
